name: "bronze_not_sent"
type: "custom"
ingestion_columns: true
execution_columns: true
from:
    path: "s3://data-raw-zone-will-{env}/salesforce/NOTSENT/{day}-{month}-{year}/*.csv"
    type: "csv"
    sep: "|"
to:
    path: "s3://data-bronze-zone-will-prod/comunicacoes_bronze/notsent/"
    type: "table"
    database: "comunicacoes_bronze"
    table_name: "not_sent_sfi"
    mode: "overwrite"
    partition_by: ["execution_year", "execution_month", "execution_day"]
