name: "bronze_inbound_wa"
type: "custom"
ingestion_columns: true
execution_columns: true
from:
    path: "s3://data-raw-zone-will-{env}/salesforce/INBOUNDWA/{day}-{month}-{year}/*.csv"
    type: "csv"
    sep: "|"
to:
    path: "s3://data-bronze-zone-will-prod/comunicacoes_bronze/inbound_wa/"
    type: "table"
    database: "comunicacoes_bronze"
    table_name: "inbound_wa_sfi"
    mode: "append"
    partition_by: ["execution_year", "execution_month", "execution_day"]
